### ISSUE TITLE
Add option to log to stderr instead of syslog

### ISSUE THREAD

**Issue by joachimmetz** [rjhansen/nsrlsvr#10]
It is currently hard to troubleshoot nsrlsvr, please add an option to log to stderr instead of syslog

**Comment by rjhansen** [comment]
Can't be done.  Daemons are required to close stdio as part of the daemonization process; there's literally no stderr for it to write to.  However, an option could be added to log to a specific file, not just syslog.  Would this be useful for you?

**Comment by joachimmetz** [comment]
What you propose in https://github.com/rjhansen/nsrlsvr/issues/11, I was looking for.

> I could add a --dry-run option, which would (a) not daemonize (b) print to stderr instead of syslog and (c) abort once it stood up. 

allowing writing to a log file is also a good idea in case you don't have syslog.

**Comment by rjhansen** [comment]
<syslog.h> is a required header for UNIX compliance.  If you're on a UNIX, it exists.

http://pubs.opengroup.org/onlinepubs/009695399/basedefs/syslog.h.html

**Comment by joachimmetz** [comment]
> <syslog.h> is a required header for UNIX compliance. If you're on a UNIX, it exists.

I understand this header would be available on most NIX-es. I was thinking more along the line of running minimalistic Linux inside VMs/container without syslogd or equiv. The code might compile but logs are not written via syslog, hence being able to write a logfile could be a useful functionality.

**Comment by rjhansen** [comment]
Nope, this is a WONTFIX.

The problem comes from the fact nsrlsvr spawns multiple processes to handle incoming requests.  If they're all trying to write to the same log file (or the same stdout handle), there will be race conditions, problems with interleaving, and more.  The log file cannot be consistent in such a case.  syslog is specifically designed to avoid this problem.

This enhancement would create inaccurate logging, so -- WONTFIX.

**Comment by joachimmetz** [comment]
Ack, just as a side note

> If they're all trying to write to the same log file (or the same stdout handle), there will be race conditions, problems with interleaving, and more.

Depending on how volume your logging is they don't need to write to the same file, you could have a log per PID. Or you could use a bit of IPC.

**Comment by rjhansen** [comment]
log-per-PID is a nonstarter due to filesystem limits.  (Some have ridiculously small limits; NTFS allows a max of 4096 files per directory.  ext2/ext3 are better but still small, at about 60,000 files per dir.)  To get around this you could always create a hierarchy of log dirs, but at that point you're talking about adding a lot of complexity for a feature which, as of right now, only you're requesting, and even then it's not a blocker for you.

IPC would add a significant amount of complexity to a small and readable codebase.  If there's a strong demand for it, sure -- but there isn't right now, so no, it won't be done.

WONTFIX.  Let it go, man.  :)

**Comment by joachimmetz** [comment]
> WONTFIX. Let it go, man. :)

No worries, no blocker for me, just providing some alternative suggestions as a side note.
Thanks for adding your perspective on the matter.
