### ISSUE TITLE
nsrlupdate hash db storage location?

### ISSUE THREAD

**Issue by botnag** [rjhansen/nsrlsvr#7]
I am trying to set up a new instance of the release 1.4 nsrlsvr, and was wondering if it was possible to control the destination of the hashes database file (e.g. /usr/local/share/nsrlsvr/hashes.txt by default) when using nsrlupdate and specifying a hashset? (I am giving it the full RDS which is quite large and running into disk space issues with the VM I am using)

I also noticed that the installation instructions have been updated, and now mention:

    6.  To create the data file, use nsrlupdate.  E.g., if your RDS is
    stored at /home/rjh/RDS_247m/NSRLFile.txt:

    $ sudo nsrlupdate /home/rjh/RDS_247m/NSRLFile.txt

However in 1.4, nsrlupdate is expecting a zip file when you point it to the hash file directly, and even then the zip file has to have the structure "minimal/NSRLFile.txt". Is this expected behaviour or are the instructions for a different version?

(using Ubuntu 14.04)

**Comment by rjhansen** [comment]
There are a few questions in there: let me try to unpack each in turn.

1.  In 1.4, the file is $PREFIX/share/nsrlsvr/NSRLFile.txt.  However, since many users were confused ("why doesn't NSRLFile.txt from the RDS distribution work when I drop it in that directory?"), in current -master the file is $PREFIX/share/nsrlsvr/hashes.txt.

2.  In 1.4 it was expecting a zip file.  However, this was made head-pounding-on-desk hard by the failure of some operating systems (I'm looking at you, Apple!) to ship modern ZIP libraries that could handle the ZIP64 file extensions NIST uses to package the RDS.  So in -master that was changed so that you had to uncompress it yourself manually first.  I foolishly thought this would solve the problem.

3.  Instead, I'm getting emails from OS X users telling me they can't uncompress the RDS file they downloaded from NIST, and apparently thinking that it's somehow my problem or that I need to fix it.  *headdesk*

4.  With respect to 1.4 expecting there to be a certain directory structure in the RDS zip file, correct.  NIST used a specific layout up through RDS 2.46; there was always a subdirectory, minimal/, and the file NSRLFile.txt was always found within that.  With RDS 2.47 NIST changed the layout.  So it's good I removed direct ZIP file support.  On the down side, it also means the nsrlupdate script shipped in 1.4 won't work with RDS 2.47 or later.

5.  I'm very grateful to NIST for their work compiling the RDS.  However, between them changing their packaging standards and other OSes not shipping ZIP64 file extensions and the Python 2->3 changeover, my days now involve me pounding my head on the desk a lot.  :)
